# branches to build

# configuration for "master" branch
# build in Release mode and deploy to Azure
-
  branches:
    only:
      - master
  image: Visual Studio 2015
  environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  version: 1.0.{build}
  configuration: Release
  platform: Any CPU
  skip_branch_with_pr: false
  before_build:
    - cmd: dotnet restore

